version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-image:latest
    command: ["/app"]
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3
      - AWS_REGION=$AWS_REGION
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME=$BUCKET_NAME
      - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
      - CLERK_WEBHOOK_SECRET=$CLERK_WEBHOOK_SECRET
      - RESEND_API_KEY=$RESEND_API_KEY
      - SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
