version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: atridad:latest
    command: ["/app"]
    pull_policy: build
    ports:
      - "3000:3000"
    networks:
      - proxy_default
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_ENDPOINT_URL_S3=$AWS_ENDPOINT_URL_S3
      - AWS_REGION=$AWS_REGION
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME=$BUCKET_NAME
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

networks:
  proxy_default:
    name: proxy_default
    external: true
