services:
  app:
    image: registry.digitalocean.com/himboapps/atridotdad:latest
    command: ["/app"]
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
