services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: atridad:latest
    command: ["/app"]
    pull_policy: build
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
