# fly.toml app configuration file generated for atridad on 2023-12-17T17:25:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "atridad"
primary_region = "sea"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256